export default {
  container: [
    "p-6",
    "sm:w-full",
    "md:w-7/12",
    "bg-gray-800",
    "rounded-xl",
    "flex-col",
    "justify-between",
    "mt-16",
  ].join(" "),
  btnContainer: [
    "flex",
    "justify-between",
    "w-full",
    "content-center",
    "mb-7",
  ].join(" "),
  btn: [
    "font-semibold",
    "flex",
    "justify-center",
    "text-gray-300",
    "border-2",
    "rounded-xl",
    "w-80",
    "flex-col",
    "items-center",
    "py-3",
    "cursor-pointer",
  ].join(" "),
  btnSubtitle: ["text-large", "leading-4", "text-gray-500"].join(" "),
  or: ["text-xl", "text-gray-500", "flex", "items-center"].join(" "),
  btnTitle: ["text-2xl", "leading-tight"].join(" "),
  isSelected: "border-bright-green duration-200",
  tokenInput: ["w-full", "bg-black-700", "h-16", "rounded-2xl"].join(" "),
};
